Retornando empregado
SELECT * FROM EMPREGADO;

Retornando colunas especificas
SELECT ID, PRIM_NOME, ULT_NOME  FROM EMPREGADO;

Retornando salario anual
SELECT ID, PRIM_NOME,SALARIO, SALARIO * 40 /3 AS "Salário Anual" FROM EMPREGADO;

Retornando o nome completo do empregado
SELECT PRIM_NOME ||ULT_NOME  FROM EMPREGADO

SELECT PRIM_NOME ||' '||ULT_NOME  FROM EMPREGADO

Criando alias
SELECT PRIM_NOME|| ' ' ||ULT_NOME  AS "NOME COMPLETO"
FROM EMPREGADO

SELECT PRIM_NOME|| ' ' ||ULT_NOME   NOME_COMPLETO
FROM EMPREGADO

SELECT SEM FROM

SELECT 'ALO', 9 + 5, NOW()

SELECT 'ALO', 9 + 5, NOW()
FROM EMPREGADO

Funcoeses de grupo

SELECT AVG(SALARIO), SUM(SALARIO), MAX(SALARIO), MIN(SALARIO), COUNT(*)
FROM EMPREGADO

SELECT MAX(SALARIO), MIN(SALARIO), 
       MAX(ULT_NOME), MIN(ULT_NOME),
	 MAX(DT_ADMISSAO), MIN(DT_ADMISSAO)
FROM EMPREGADO
