-- Comando para criar a tabela nivel
CREATE TABLE NIVEL(
	CODIGONIVEL int NOT NULL,
	DESCRICAO varchar(90) NOT NULL,
	CONSTRAINT CHAVEPNIVEL PRIMARY KEY (CODIGONIVEL)
);

-- Comando para criar a tabela curso
CREATE TABLE CURSO(
	CODIGOCURSO int NOT NULL,
	NOME varchar(90) NOT NULL UNIQUE,
	DATACRIACAO date NULL,
	CODIGONIVEL int NULL,
	CONSTRAINT CHAVEPCURSO PRIMARY KEY (CODIGOCURSO),
	FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL (CODIGONIVEL)
)