SELECT
COUNT(*) AS "Número de Alunos",
MIN(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Menor de Idade",
AVG(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Idade Média",
MAX(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Maior Idade",
SUM(EXTRACT(YEAR FROM AGE(DTNASCIMENTO))) AS "Soma Idade"
FROM ALUNO;

SELECT COUNT(*), COUNT(NOME), COUNT(EMAIL) FROM ALUNO

SELECT MIN(NOME), MAX(NOME),
	   MIN(DTNASCIMENTO), MAX(DTNASCIMENTO),
	   MIN(CODIGOALUNO), MAX(CODIGOALUNO)
FROM ALUNO 

CREATE TABLE LETRA
(LET CHAR(1));

INSERT INTO LETRA VALUES ('y');
INSERT INTO LETRA VALUES ('z');
INSERT INTO LETRA VALUES ('A');
INSERT INTO LETRA VALUES ('B');
SELECT MIN(LET),MAX(LET) FROM LETRA

SELECT * FROM LETRA

INSERT INTO LETRA VALUES ('Z');
INSERT INTO LETRA VALUES ('a');
SELECT MIN(LET),MAX(LET) FROM LETRA

SELECT * FROM LETRA
ORDER BY 1

CREATE TABLE DISCIPLINA
( COD INT PRIMARY KEY,
  NOME VARCHAR(30));
INSERT INTO DISCIPLINA VALUES (1,'D1');
INSERT INTO DISCIPLINA VALUES (2,'D2');
INSERT INTO DISCIPLINA VALUES (3,'D3');
INSERT INTO DISCIPLINA VALUES (4,'D4');

CREATE TABLE CURSO
( COD INT PRIMARY KEY,
  NOME VARCHAR(30));
INSERT INTO CURSO VALUES (1,'C1');
INSERT INTO CURSO VALUES (2,'C2');

SELECT COUNT(*) NCURSOS FROM CURSO;
SELECT COUNT(*) NDISCIPLINAS FROM DISCIPLINA;
SELECT COUNT(*) NALUNOS FROM ALUNO;

SELECT
(SELECT COUNT(*) NCURSOS FROM CURSO),
(SELECT COUNT(*) NALUNOS FROM ALUNO),
(SELECT COUNT(*) NDISCIPLINAS FROM DISCIPLINA);