CREATE TABLE NIVEL (
        CODIGONIVEL int NOT NULL,
        DESCRICAO varchar(90) NOT NULL,
        CONSTRAINT CHAVEPNIVEL PRIMARY KEY (CODIGONIVEL));
CREATE TABLE CURSO (
        CODIGOCURSO int NOT NULL,
        NOME varchar(90) NOT NULL UNIQUE,
        DATACRIACAO date NULL,
        CODIGONIVEL int NULL,
        CONSTRAINT CHAVEPCURSO PRIMARY KEY (CODIGOCURSO));
ALTER TABLE CURSO ADD FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL;
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (1,'Graduação');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (2,'Especialização');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (3,'Mestrado');
INSERT INTO NIVEL (CODIGONIVEL, DESCRICAO) VALUES (4,'Doutorado');
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (1, 'Sistemas de Informação', '19/06/1999',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (2, 'Medicina', '10/05/1990',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (3, 'Nutrição', '19/02/2012',NULL);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (4, 'Pedagogia','19/06/1999',1);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (5, 'Saúde da Família','10/09/1999',3);
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO, CODIGONIVEL) VALUES (6, 'Computacão Aplicada','10/09/1999', NULL);

SELECT * FROM NIVEL
SELECT * FROM CURSO
SELECT * FROM NIVEL, CURSO
SELECT * FROM CURSO CROSS JOIN NIVEL