SELECT * FROM NIVEL
SELECT * FROM CURSO

SELECT *
FROM CURSO, NIVEL
WHERE NIVEL.CODIGONIVEL=CURSO.CODIGONIVEL;

SELECT * 
FROM CURSO
INNER JOIN NIVEL ON (NIVEL.CODIGONIVEL=CURSO.CODIGONIVEL);

SELECT *
FROM CURSO
INNER JOIN NIVEL USING(CODIGONIVEL);

SELECT *
FROM CURSO
NATURAL JOIN NIVEL

SELECT CURSO.CODIGOCURSO, CURSO.NOME, NIVEL.CODIGONIVEL,
NIVEL.DESCRICAO FROM CURSO INNER JOIN NIVEL ON (NIVEL.CODIGONIVEL=CURSO.CODIGONIVEL);

SELECT C.CODIGOCURSO, C.NOME, N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C INNER JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGONIVEL);

SELECT C.CODIGOCURSO, C.NOME, N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C INNER JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGOCURSO);