SELECT * FROM AUTORES A
INNER JOIN OBRAS O
ON A.CODIGO = O.AUTOR

SELECT *
FROM AUTORES A
INNER JOIN OBRAS O
ON A.CODIGO = O.AUTOR
WHERE SALAO = 36 AND ANO BETWEEN 1965 AND 1975

SELECT DISTINCT A.NOME, A.NACIONALIDADE
FROM AUTORES A
INNER JOIN OBRAS O 
ON A.CODIGO = O.AUTOR

SELECT O.CODIGO, O.TITULO
FROM AUTORES A
INNER JOIN OBRAS O
INNER JOIN SALOES S ON S.NUMERO = O.SALAO
ON A.CODIGO = O.AUTOR
WHERE UPPER(A.NOME) = 'PABLO PICASSO' AND S.ANDAR = 3

SELECT A.NOME, A.NACIONALIDADE, O.TITULO, P.ESTILO
FROM AUTORES A
INNER JOIN OBRAS O ON A.CODIGO = O.AUTOR
INNER JOIN PINTURAS P ON P.CODIGO = O.CODIGO

SELECT O.TITULO, P.ESTILO
FROM OBRAS O
INNER JOIN PINTURAS P USING(CODIGO)