SELECT C.CODIGOCURSO, C.NOME,
N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C LEFT JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGONIVEL) ;

SELECT C.CODIGOCURSO, C.NOME,
N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C RIGHT JOIN NIVEL N ON
(N.CODIGONIVEL=C.CODIGONIVEL);

SELECT C.CODIGOCURSO, C.NOME,
N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C LEFT JOIN NIVEL N ON (N.CODIGONIVEL=C.CODIGONIVEL);

SELECT C.CODIGOCURSO, C.NOME,
    N.CODIGONIVEL, N.DESCRICAO
FROM NIVEL N RIGHT JOIN CURSO C ON (N.CODIGONIVEL=C.CODIGONIVEL);

SELECT C.CODIGOCURSO, C.NOME,
N.CODIGONIVEL, N.DESCRICAO
FROM CURSO C FULL OUTER JOIN NIVEL N ON
(N.CODIGONIVEL=C.CODIGONIVEL);
