CREATE TABLE TABTRANS(
C1 INTEGER,
C2 VARCHAR(10));

SELECT * FROM TABTRANS

BEGIN;
INSERT INTO TABTRANS VALUES (1, 'A');
INSERT INTO TABTRANS VALUES (2, 'B');
COMMIT
SELECT * FROM TABTRANS;

BEGIN;
INSERT INTO TABTRANS VALUES (3, 'C');
INSERT INTO TABTRANS VALUES (4, 'D');
SAVEPOINT B;
SELECT * FROM TABTRANS;
ROLLBACK TO SAVEPOINT A;
SELECT * FROM TABTRANS;

DELETE FROM TABTRANS;